apiVersion: v1
kind: Namespace
metadata:
  name: tomcat
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tomcat
  name: my-tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: 811636332895.dkr.ecr.ap-southeast-1.amazonaws.com/tomcat
      imagePullSecrets:
      - name: ${ap-southeast-1}-ecr-registry
        ports:
          - containerPort: 8090         
---

apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: tomcat 
  labels:
  annotations:
     app.kubernetes.io/name: ingress-nginx
     app.kubernetes.io/part-of: ingress-nginx
spec:
  externalTrafficPolicy: Local
  type: nlb
  selector:
    app: tomcat
  ports:
    - name: tomcat
      port: 8090
      
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: tomcat
 
spec:
  rules:
  - http:
      paths:
        - path: /tomcat
          backend:
            serviceName: svc
            servicePort: 809i0
