apiVersion: v1
kind: Namespace
metadata:
  name: tomcat
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tomcat
  name: my-tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: 811636332895.dkr.ecr.ap-southeast-1.amazonaws.com/tomcat
        ports:
        - containerPort: 8090
---

apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: tomcat 
  labels:
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:      
  selector:
    app: tomcat
  ports:
    - name: tomcat
      port: 8085
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: tomcat
  annotations:
    ingress.kubernetes.io/rewrite-target: / 
spec:
  rules:
  - http:
      paths:
        - path: /tomcat
          backend:
            serviceName: svc
            servicePort: 8085
