apiVersion: apps/v1
kind: Deployment
metadata:
 name: tomcat1
 namespace: tomcat1
 labels:
   app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat1
        image: 811636332895.dkr.ecr.ap-southeast-1.amazonaws.com/tomcat
        ports:
        - containerPort: 80
