apiVersion: v1
kind: Namespace
metadata:
  name: tomcat
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tomcat
  name: tomcat1
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: 811636332895.dkr.ecr.ap-southeast-1.amazonaws.com/tomcat
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: service
metadata:
  name: service
  namespce: tomcat

spec:
  selector:
    app: tomcat
ports:
    - port: 5678
      type: LoadBalancer
