- name: deployment of package
  hosts: web
  become: yes
  tasks:
  - name: stop the apache
    service :
      name: httpd
      state: stopped
  - name: zip file
    copy:
      src: weblayer-build.zip
      dest: /tmp
  - name: unzip the file
    unarchive:
      src: /tmp/weblayer-build.zip
      dest: /var/www/html
      remote_src: yes
  - name: start httpd
    service:
      name: httpd
      state: started
