apiVersion: v1
kind: Deployment
metadata:
 name: apache
 name space: apache
 labels:
   app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: apache
        image: 811636332895.dkr.ecr.ap-southeast-1.amazonaws.com/tomcat
        ports:
        - containerPort: 80
