- name: deploy package
  hosts: dev
  become: yes
  tasks:
  - name: install java
    yum:
      name: java 1.8.0
      state: present
  - name: create user
    user:
      name: tomcat
  - name: create a dirctory
    file:
      path: /tomcat
      owner: tomcat
      group: tomcat
      mode:   0775
      state: directory
  - name: download and omcar
    get_url:
      url: http://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.27/bin/apache-tomcat-9.0.27.tar.gz
      dest: /tomcat
    become_user: tomcat

  - name: extrace tomcat
    unarchive:
      src: /tomcat/apache-tomcat-9.0.27.tar.gz
      dest: /tomcat
      remote_src: yes
  - name: start the tomacr apache
    shell: ./startup.sh
    args:
      chdir: /tomcat/apache-tomcat-9.0.26/bin    
     
