---
- name: Ensure apache is installed and started
  hosts: web
  user: root
  become: yes

  tasks:
- name: Ensure httpd package is present
  yum:
    name: httpd
    state: present
- name: Ensure httpd is started
  service:
    name: httpd
    state: started
